// Validation of the JavaScript model against pvlib reference values
// (test/fixtures/pvlib-reference.json, generated by scripts/dev/make-pvlib-fixtures.py).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { solarPosition, relativeAirmass, extraterrestrialDni, RAD, DEG } from '../public/js/model/solar-position.js';
import { perezCoefficients, perezComponents } from '../public/js/model/perez.js';
import { iamAshrae, diffuseIamTable, lookupIam } from '../public/js/model/iam.js';
import { cosAoi, trackerAngle, rowViewFactors, shadedFraction } from '../public/js/model/geometry.js';
import { prepareHourly, simulate, optimalTilt } from '../public/js/model/simulate.js';
import { DEFAULT_PARAMS, stagesFromFields } from '../public/js/model/losses.js';
import { parsePvgisTmy, estimateTimeShift } from '../public/js/pvgis.js';
import { syntheticPvgisTmy } from '../scripts/dev/synthetic-tmy.mjs';

const ref = JSON.parse(readFileSync(new URL('./fixtures/pvlib-reference.json', import.meta.url)));
const angDiff = (a, b) => Math.abs(((a - b + 540) % 360) - 180);

test('solar position matches pvlib SPA within 0.02°', () => {
  for (const r of ref.solarPosition) {
    const sp = solarPosition(r.timeMs, r.lat, r.lon);
    assert.ok(Math.abs(sp.zenith - r.zenith) < 0.02, `zenith ${sp.zenith} vs ${r.zenith}`);
    if (r.zenith < 89) assert.ok(angDiff(sp.azimuth, r.azimuth) < 0.05, `azimuth ${sp.azimuth} vs ${r.azimuth}`);
  }
});

test('Perez components match pvlib', () => {
  const out = {};
  for (const r of ref.perez) {
    assert.ok(Math.abs(relativeAirmass(r.zenith) - r.airmass) < 1e-9 * r.airmass);
    const z = r.zenith * RAD;
    const s = { E: Math.sin(z) * Math.sin(r.solarAzimuth * RAD), N: Math.sin(z) * Math.cos(r.solarAzimuth * RAD), U: Math.cos(z) };
    const b = r.tilt * RAD, a = r.surfaceAzimuth * RAD;
    const ca = cosAoi(s.E, s.N, s.U, Math.sin(b), Math.cos(b), Math.sin(a), Math.cos(a));
    assert.ok(Math.abs(Math.acos(Math.max(-1, Math.min(1, ca))) * DEG - r.aoi) < 1e-6);
    const c = perezCoefficients(r.dhi, r.dni, z, r.airmass, extraterrestrialDni(r.doy));
    perezComponents(r.dhi, c.F1, c.F2, ca, s.U, Math.cos(b), Math.sin(b), out);
    for (const k of ['iso', 'cs', 'hz']) {
      assert.ok(Math.abs(out[k] - r[k]) < 1e-6 * Math.max(1, Math.abs(r[k])), `${k} ${out[k]} vs ${r[k]}`);
    }
  }
});

test('single-axis tracker angles match pvlib.tracking.singleaxis', () => {
  for (const r of ref.tracker) {
    const z = r.zenith * RAD;
    const sE = Math.sin(z) * Math.sin(r.solarAzimuth * RAD);
    const sU = Math.cos(z);
    const theta = trackerAngle(sE, sU, r.limit * RAD, r.gcr, r.backtrack) * DEG;
    // pvlib: positive = west-facing for axis_azimuth 180; ours: positive = east-facing.
    assert.ok(Math.abs(theta + r.theta) < 1e-6, `theta ${theta} vs ${-r.theta}`);
    assert.ok(Math.abs(Math.abs(theta) - r.surfaceTilt) < 1e-6);
  }
});

test('ASHRAE IAM and integrated diffuse IAM agree with pvlib (Marion)', () => {
  for (const r of ref.iamAshrae) assert.ok(Math.abs(iamAshrae(Math.cos(r.aoi * RAD), 0.05) - r.iam) < 1e-9);
  const t = diffuseIamTable(0.05);
  for (const r of ref.marionDiffuse) {
    if (r.tilt < 5) continue;
    assert.ok(Math.abs(lookupIam(t.sky, r.tilt) - r.sky) < 0.002, `sky @${r.tilt}`);
    assert.ok(Math.abs(lookupIam(t.gnd, r.tilt) - r.ground) < 0.01, `ground @${r.tilt}`);
    assert.ok(Math.abs(lookupIam(t.hz, r.tilt) - r.horizon) < 0.03, `horizon @${r.tilt}`);
  }
});

test('row view factors: limits and closure', () => {
  const b = 25 * RAD;
  const free = rowViewFactors(Math.cos(b), Math.sin(b), Infinity, Infinity);
  assert.ok(Math.abs(free.sky - (1 + Math.cos(b)) / 2) < 1e-12);
  const far = rowViewFactors(Math.cos(b), Math.sin(b), 1e6, 1e6);
  assert.ok(Math.abs(far.sky - free.sky) < 1e-5 && Math.abs(far.gnd - free.gnd) < 1e-5);
  const rows = rowViewFactors(Math.cos(b), Math.sin(b), 2.5, 2.5);
  assert.ok(rows.sky < free.sky && rows.gnd < free.gnd && rows.sky + rows.gnd <= 1);
  const flat = rowViewFactors(1, 0, 2, 2);
  assert.ok(Math.abs(flat.sky - 1) < 1e-12 && Math.abs(flat.gnd) < 1e-12);
  // E-W tents with no gap between them see no ground.
  assert.ok(Math.abs(rowViewFactors(Math.cos(b), Math.sin(b), 2 * Math.cos(b), 0).gnd) < 1e-12);
});

test('beam shading fraction: geometry', () => {
  const b = 30 * RAD;
  // Sun along the normal: rows 1 slant width apart still overlap (their spacing
  // seen from the sun is p·sinψ = cos β); from p = 1/cos β on there is no shade.
  assert.ok(Math.abs(shadedFraction(Math.sin(b), Math.cos(b), Math.cos(b), Math.sin(b), 1.0) - (1 - Math.cos(b))) < 1e-12);
  assert.equal(shadedFraction(Math.sin(b), Math.cos(b), Math.cos(b), Math.sin(b), 1 / Math.cos(b) + 1e-9), 0);
  // Profile angle 10°, pitch 2.5: fs = 1 - p sinψ / sin(ψ+β).
  const psi = 10 * RAD;
  const fs = shadedFraction(Math.cos(psi), Math.sin(psi), Math.cos(b), Math.sin(b), 2.5);
  assert.ok(Math.abs(fs - (1 - (2.5 * Math.sin(psi)) / Math.sin(psi + b))) < 1e-12);
  assert.equal(shadedFraction(1, 0.5, 1, 0, Infinity), 0);
});

test('full chain (fixed plane) matches pvlib Perez + Marion IAM + PVsyst cell temperature', () => {
  const c = ref.chain;
  const tmy = parsePvgisTmy(syntheticPvgisTmy(c.lat, c.lon, { offsetMin: c.offsetMin }));
  const h = prepareHourly(tmy, c.offsetMin);
  const p = { ...DEFAULT_PARAMS, albedo: c.albedo, b0: c.b0, soiling: c.soiling };
  const r = simulate(h, { type: 'fixed', tilt: c.tilt, gcr: 0 }, p);
  const rel = (a, b) => Math.abs(a / b - 1);
  assert.ok(rel(r.stages.ghi, c.ghi) < 1e-4, `ghi ${r.stages.ghi} vs ${c.ghi}`);
  assert.ok(rel(r.stages.inc, c.inc) < 0.002, `inc ${r.stages.inc} vs ${c.inc}`);
  assert.ok(rel(r.stages.eff, c.effMarion) < 0.002, `eff ${r.stages.eff} vs ${c.effMarion}`);
  assert.ok(rel(r.stages.temp, c.temp) < 0.002, `temp ${r.stages.temp} vs ${c.temp}`);
});

test('time-shift detection recovers the offset of the irradiance time stamps', () => {
  for (const off of [-30, 0, 10, 30]) {
    const tmy = parsePvgisTmy(syntheticPvgisTmy(-12, 40, { offsetMin: off }));
    assert.equal(estimateTimeShift(tmy).shift, off);
  }
});

test('precomputed grid sums reproduce the hourly simulation', () => {
  const tmy = parsePvgisTmy(syntheticPvgisTmy(38, -5, { offsetMin: 10 }));
  const h = prepareHourly(tmy, 10);
  const mounts = [
    { type: 'fixed', tilt: 30, gcr: 0.4 },
    { type: 'ew', tilt: 15, gcr: 0.85 },
    { type: 'tracker', limit: 55, gcr: 0.35, backtrack: true },
    { type: 'tracker', limit: 60, gcr: 0.4, backtrack: false },
  ];
  for (const m of mounts) {
    const f = simulate(h, m, DEFAULT_PARAMS).fields;
    // Exact at the reference albedo/b0 with Uv = 0, whatever the other parameters are.
    const p1 = { ...DEFAULT_PARAMS, uc: 20, gamma: -0.29, soiling: 4, inverterEff: 97 };
    const exact = simulate(h, m, p1).yield;
    assert.ok(Math.abs(stagesFromFields(f, p1).avail / exact - 1) < 1e-9);
    // Linearised albedo / b0 dependence: within 0.3 %.
    const p2 = { ...DEFAULT_PARAMS, albedo: 0.35, b0: 0.03 };
    const approx = stagesFromFields(f, p2).avail;
    const full = simulate(h, m, p2).yield;
    assert.ok(Math.abs(approx / full - 1) < 0.003, `${JSON.stringify(m)}: ${approx} vs ${full}`);
  }
});

test('physical sanity: trackers beat fixed, rows cost yield, optimum tilt near latitude', () => {
  const tmy = parsePvgisTmy(syntheticPvgisTmy(35, 20, { offsetMin: 0 }));
  const h = prepareHourly(tmy, 0);
  const p = DEFAULT_PARAMS;
  const opt = optimalTilt(h, { type: 'fixed', gcr: 0 }, p);
  assert.ok(opt.tilt > 20 && opt.tilt < 40, `optimal tilt ${opt.tilt}`);
  const trk = simulate(h, { type: 'tracker', limit: 60, gcr: 0.35, backtrack: true }, p).yield;
  assert.ok(trk > opt.result.yield * 1.1);
  const iso = simulate(h, { type: 'fixed', tilt: 30, gcr: 0 }, p).yield;
  const dense = simulate(h, { type: 'fixed', tilt: 30, gcr: 0.5 }, p).yield;
  assert.ok(dense < iso);
  const bt = simulate(h, { type: 'tracker', limit: 60, gcr: 0.4, backtrack: true }, p).yield;
  const nobt = simulate(h, { type: 'tracker', limit: 60, gcr: 0.4, backtrack: false }, p).yield;
  assert.ok(bt > nobt, 'backtracking should beat shaded true tracking');
});
